### ISSUE TITLE
Shake&Tune halting startup without accelerometer connected

### ISSUE THREAD

**Issue by SelfDestructor** [Frix-x/klippain-shaketune#186]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

 v5.0.0-0-g74364d72 

### Describe the bug and expected behavior

Hi! I just updated Shake&Tune and I'm now unable to start my printer because of the following error:

No [resonance_tester] config section found in printer.cfg! Please add one to use Shake&Tune!

I don't have an accelerometer permanently attached to my printer which was not an issue with the old version.

I have not specified [shaketune] in my printer config.

### Additional information and klippy.log

Config error
Traceback (most recent call last):
  File "/home/chris/klipper/klippy/klippy.py", line 135, in _connect
    cb()
  File "/home/chris/klipper/klippy/extras/shaketune/shaketune.py", line 143, in _on_klippy_connect
    raise self._config.error(
configparser.Error: No [resonance_tester] config section found in printer.cfg! Please add one to use Shake&Tune!

**Comment by SelfDestructor** [comment]
Never mind. There was a rogue [shaketune] hidden in the configuration file somewhere it shouldn't have been.
