### ISSUE TITLE
error after updating 

### ISSUE THREAD

**Issue by jpbnto** [Frix-x/klippain-shaketune#24]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v2.0.0-0-gc7e39da5

### Describe the bug and expected behavior

10:22:12 AM
Writing raw accelerometer data to /tmp/raw_data_y_y.csv file
10:22:12 AM
echo: Y axis frequency profile generation...
10:22:12 AM
echo: This may take some time (1-3min)
10:22:12 AM
Running Command {shaketune}...:
10:22:12 AM
/home/pi/printer_data/config/K-ShakeTune/scripts/shaketune.sh: line 3: /home/pi/klippain_shaketune-env/bin/activate: No such file or directory
10:22:13 AM
Traceback (most recent call last):
File "/home/pi/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 30, in
10:22:13 AM
from graph_belts import belts_calibration
File "/home/pi/klippain_shaketune/K-ShakeTune/scripts/graph_belts.py", line 17, in
import scipy
ModuleNotFoundError: No module named 'scipy'
10:22:13 AM
/home/pi/printer_data/config/K-ShakeTune/scripts/shaketune.sh: line 5: deactivate: command not found
10:22:13 AM
Command {shaketune} finished
[klippy.log](https://github.com/Frix-x/klippain-shaketune/files/13655188/klippy.log)

**Comment by jpbnto** [comment]
update:

I reinstalled the latest version via SSH. It is working now.
