### ISSUE TITLE
Vibration Graph Exception: could not convert string to float: 'freq'

### ISSUE THREAD

**Issue by BassXX** [Frix-x/klippain-shaketune#52]
### K-Shake&Tune module branch

- [x] I confirm using the main branch

### Version

v2.5.0-3-geab10ce5

### Describe the bug and expected behavior

Hello, Shaketune won´t create a vibrations graph for me. This is the console output.

ValueError: could not convert string to float: 'freq'

The above exception was the direct cause of the following exception:

-------------------------------------------------------------------------------------------
Traceback (most recent call last):
File "/home/pi/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 299, in

main()
File "/home/pi/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 288, in main
create_vibrations_graph(axis_name=options.axis_name, accel=options.accel_used, chip_name=options.chip_name, keep_csv=options.keep_csv)
File "/home/pi/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 165, in create_vibrations_graph
fig = vibrations_calibration(lognames, KLIPPER_FOLDER, axis_name, accel)
File "/home/pi/klippain_shaketune/K-ShakeTune/scripts/graph_vibrations.py", line 352, in vibrations_calibration
raw_datas = [parse_log(filename) for filename in lognames]
File "/home/pi/klippain_shaketune/K-ShakeTune/scripts/graph_vibrations.py", line 352, in
raw_datas = [parse_log(filename) for filename in lognames]
File "/home/pi/klippain_shaketune/K-ShakeTune/scripts/common_func.py", line 22, in parse_log
return np.loadtxt(logname, comments='#', delimiter=',')
File "/home/pi/klippain_shaketune-env/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt

arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
File "/home/pi/klippain_shaketune-env/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1016, in _read

arr = _load_from_filelike(
ValueError: could not convert string 'freq' to float64 at row 0, column 1.

-----------------------------------------------------------------------------------------

I am using beacon´s built in Accelerometer

Thanks & Regards

**Comment by BassXX** [comment]
Ok does not matter. Simply re-running the vibration calibration was successful.
